
project_id = "oshwukedwbortdxknolz"

[functions."create-checkout"]
verify_jwt = true

[functions."customer-portal"]
verify_jwt = true

[functions."check-subscription"]
verify_jwt = true

[functions."ai-course"]
verify_jwt = true

[functions."ai-assistant"]
verify_jwt = true

