
project_id = "oshwukedwbortdxknolz"

[api]
enabled = true
port = 54321
schemas = [ ]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[realtime]
enabled = true

[edge_functions]
enabled = true

[edge_functions.create-checkout]
verify_jwt = true

[edge_functions.customer-portal]
verify_jwt = true

[edge_functions.check-subscription]
verify_jwt = true
